import { initializeApp } from "https://www.gstatic.com/firebasejs/12.15.0/firebase-app.js";
import { getFirestore, collection, doc, getDoc, getDocs, setDoc, addDoc, updateDoc, query, where, serverTimestamp, Timestamp } from "https://www.gstatic.com/firebasejs/12.15.0/firebase-firestore.js";

const firebaseConfig={apiKey:"AIzaSyCWD3utr1FC1pIGZ1A9mvurPNkN3ndZZlo",authDomain:"cognitus-pay.firebaseapp.com",projectId:"cognitus-pay",storageBucket:"cognitus-pay.firebasestorage.app",messagingSenderId:"89172973354",appId:"1:89172973354:web:2be42b5279a45052acb053"};
const app=initializeApp(firebaseConfig); const db=getFirestore(app);
const $=s=>document.querySelector(s); const appEl=$("#app");
const money=n=>`R$${Number(n||0).toLocaleString()}`; const now=()=>new Date().toISOString();
const ROLE_PERMS={
  staff:["canViewOwnPayroll","canRequestPay","canRequestRaise","canRequestAdjustment"],
  financeEmployee:["canViewFinanceRecords","canMaintainFinanceRecords","canPreparePayroll"],
  fcSupervisor:["canViewFinanceRecords","canMaintainFinanceRecords","canPreparePayroll","canAdjustPayroll"],
  cfo:["canViewFinanceRecords","canMaintainFinanceRecords","canPreparePayroll","canAdjustPayroll","canManagePayRates","canLockPayrollPeriod"],
  management:["canAuditEmployees","canViewManagedEmployees","canViewFinanceRecords"],
  board:["canViewFinanceRecords","canEditAnyLog","canDeleteAnyLog","canAuditEmployees"],
  executive:["canApprovePayRequests","canApproveRaises","canViewFinanceRecords","canEditAnyLog","canDeleteAnyLog","canManageUsers"],
  owner:["*"]
};
const ROLE_LABELS={staff:"Staff Member",financeEmployee:"Finance Employee",fcSupervisor:"FC Supervisor",cfo:"Chief Financial Officer",management:"Management",board:"Board of Directors",executive:"Executive",owner:"Owner"};
const STATE={user:null,page:"dashboard"};
const can=p=>STATE.user?.permissions?.includes("*")||STATE.user?.permissions?.includes(p);
async function sha256(text){const data=new TextEncoder().encode(text);const hash=await crypto.subtle.digest("SHA-256",data);return [...new Uint8Array(hash)].map(b=>b.toString(16).padStart(2,"0")).join("")}
const pinHash=(pin,salt)=>sha256(`${salt}:${pin}:cognitus-pay-v1`);
function idSeq(prefix){return `${prefix}-${Date.now().toString(36).toUpperCase().slice(-6)}${Math.floor(Math.random()*900+100)}`}
async function audit(action,details={},target="system"){try{await addDoc(collection(db,"auditLogs"),{action,target,details,actorEmployeeId:STATE.user?.employeeId||"SYSTEM",actorName:STATE.user?.employeeName||"System",createdAt:serverTimestamp(),createdAtText:now()})}catch(e){console.warn(e)}}
async function qAll(col,field,op,value){const snap=await getDocs(query(collection(db,col),where(field,op,value)));return snap.docs.map(d=>({id:d.id,...d.data()}))}
async function all(col){const snap=await getDocs(collection(db,col));return snap.docs.map(d=>({id:d.id,...d.data()}))}
async function maybeBootstrap(){const snap=await getDocs(query(collection(db,"users"),where("isBootstrapOwner","==",true)));return snap.empty}
function authScreen(mode="login",msg=""){
  appEl.innerHTML=`<main class="auth-wrap"><section class="auth-card"><div class="brand"><div class="logo">CS</div><div><h1>Cognitus Financial Portal</h1><small>Robux payroll, expenses, approvals, and audits.</small></div></div>${msg?`<div class="notice">${msg}</div>`:""}<div id="authBody"></div></section></main>`;
  if(mode==="bootstrap") return bootstrapForm(); loginForm();
}
async function init(){if(await maybeBootstrap()) authScreen("bootstrap","No Owner account exists yet. Create the protected bootstrap Owner account first."); else authScreen();}
function bootstrapForm(){ $("#authBody").innerHTML=`<form id="boot" class="grid"><h2>Owner Bootstrap</h2><div class="grid two"><label>Discord Username<input name="discordUsername" required value="Executive_Eagle"></label><label>Discord User ID<input name="discordId" required placeholder="Your numeric Discord ID"></label></div><div class="grid two"><label>Create 4-digit PIN<input name="pin" maxlength="4" pattern="[0-9]{4}" required type="password"></label><label>Confirm PIN<input name="pin2" maxlength="4" pattern="[0-9]{4}" required type="password"></label></div><button>Create Owner Account</button></form>`;
  $("#boot").onsubmit=async e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.target)); if(f.pin!==f.pin2)return alert("PINs do not match."); const salt=crypto.randomUUID(); const hash=await pinHash(f.pin,salt); const owner={employeeName:"Executive_Eagle",employeeId:"COG-EXC-001",department:"Executive",rank:"Executive_Eagle",payrollId:"CS-1205",discordUsername:f.discordUsername.trim(),discordId:f.discordId.trim(),pinHash:hash,pinSalt:salt,pinCreatedAt:serverTimestamp(),firstLoginComplete:true,accountStatus:"Active",role:"owner",permissions:["*"],payRate:0,payRateType:"Manual",payrollStatus:"Active",protectedAccount:true,cannotDelete:true,isBootstrapOwner:true,createdAt:serverTimestamp(),createdBy:"SYSTEM_BOOTSTRAP"}; await setDoc(doc(db,"users",owner.employeeId),owner); await setDoc(doc(db,"payrollProfiles",owner.payrollId),{employeeId:owner.employeeId,payrollId:owner.payrollId,currentBalance:0,lifetimePaid:0,payrollStatus:"Active",createdAt:serverTimestamp()}); await audit("bootstrap_owner_created",{employeeId:owner.employeeId,payrollId:owner.payrollId}); authScreen("login","Owner created. Sign in with your Discord Username, Discord ID, and PIN.")}
}
function loginForm(){ $("#authBody").innerHTML=`<form id="login" class="grid"><h2>Employee Login</h2><label>Discord Username<input name="discordUsername" required autocomplete="username"></label><label>Discord User ID<input name="discordId" required inputmode="numeric"></label><button>Continue</button></form>`;
  $("#login").onsubmit=async e=>{e.preventDefault(); const f=Object.fromEntries(new FormData(e.target)); const matches=await qAll("users","discordId","==",f.discordId.trim()); const user=matches.find(u=>(u.discordUsername||"").toLowerCase()===f.discordUsername.trim().toLowerCase()); if(!user)return authScreen("login","No Cognitus staff account matched that Discord Username and Discord ID."); if(["Suspended","Terminated","Archived"].includes(user.accountStatus))return authScreen("login",`This account is ${user.accountStatus} and cannot access the portal.`); STATE.user=user; if(!user.pinHash)return pinCreate(); pinEnter(); }
}
function pinCreate(){appEl.innerHTML=`<main class="auth-wrap"><section class="auth-card"><div class="brand"><div class="logo">CS</div><div><h1>First Login</h1><small>Welcome, ${STATE.user.employeeName}. Create your 4-digit PIN.</small></div></div><form id="pinCreate" class="grid"><div class="grid two"><label>New PIN<input name="pin" maxlength="4" pattern="[0-9]{4}" required type="password"></label><label>Confirm PIN<input name="pin2" maxlength="4" pattern="[0-9]{4}" required type="password"></label></div><button>Activate Account</button></form></section></main>`;$("#pinCreate").onsubmit=async e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.target));if(f.pin!==f.pin2)return alert("PINs do not match.");const salt=crypto.randomUUID(),hash=await pinHash(f.pin,salt);await updateDoc(doc(db,"users",STATE.user.employeeId),{pinHash:hash,pinSalt:salt,pinCreatedAt:serverTimestamp(),firstLoginComplete:true,accountStatus:"Active",failedPinAttempts:0,pinLockedUntil:null});STATE.user={...STATE.user,pinHash:hash,pinSalt:salt,firstLoginComplete:true,accountStatus:"Active"};await audit("pin_created",{},STATE.user.employeeId);renderApp()}}
function pinEnter(){const locked=STATE.user.pinLockedUntil?.toDate?STATE.user.pinLockedUntil.toDate():null; if(locked&&locked>new Date())return authScreen("login",`Account locked until ${locked.toLocaleTimeString()}.`); appEl.innerHTML=`<main class="auth-wrap"><section class="auth-card"><div class="brand"><div class="logo">CS</div><div><h1>Welcome back, ${STATE.user.employeeName}</h1><small>Enter your secure 4-digit PIN.</small></div></div><form id="pinEnter" class="grid"><label>PIN<input name="pin" maxlength="4" pattern="[0-9]{4}" required type="password" autofocus></label><div class="actions"><button>Enter Portal</button><button type="button" class="secondary" id="back">Back</button></div></form></section></main>`;$("#back").onclick=()=>authScreen();$("#pinEnter").onsubmit=async e=>{e.preventDefault(); const pin=new FormData(e.target).get("pin"); const hash=await pinHash(pin,STATE.user.pinSalt); if(hash!==STATE.user.pinHash){const attempts=(STATE.user.failedPinAttempts||0)+1; let patch={failedPinAttempts:attempts}; if(attempts>=5)patch.pinLockedUntil=Timestamp.fromDate(new Date(Date.now()+15*60000)); await updateDoc(doc(db,"users",STATE.user.employeeId),patch); await audit("failed_pin",{attempts},STATE.user.employeeId); return authScreen("login",attempts>=5?"Too many wrong PINs. Account locked for 15 minutes.":`Incorrect PIN. Attempt ${attempts}/5.`)} await updateDoc(doc(db,"users",STATE.user.employeeId),{failedPinAttempts:0,lastLoginAt:serverTimestamp()}); await audit("login",{},STATE.user.employeeId); renderApp();}}
function navItems(){let n=[["dashboard","Dashboard"],["myPayroll","My Payroll"],["paystubs","My Paystubs"],["payRequests","Pay Requests"],["raiseRequests","Raise Requests"],["adjustments","Adjustments"]]; if(can("canViewFinanceRecords")) n.push(["periods","Payroll Periods"],["profiles","Payroll Profiles"],["expenses","Expense Logs"],["revenue","Revenue Logs"]); if(can("canAuditEmployees")) n.push(["audits","Management Audits"]); if(can("canApprovePayRequests")||can("canApproveRaises")) n.push(["approvals","Approval Queue"]); if(can("canManageUsers")) n.push(["employees","Employees"]); if(can("canViewFinanceRecords")||can("canManageUsers")) n.push(["auditLog","Audit Log"]); return n;}
function renderApp(){appEl.innerHTML=`<div class="shell"><aside class="sidebar" id="side"><div class="side-brand"><div class="logo">CS</div><div><h2>Cognitus Pay</h2><small>Financial Portal</small></div></div><div class="user-chip"><b>${STATE.user.employeeName}</b><br><small>${STATE.user.employeeId} • ${STATE.user.payrollId}</small><br><span class="pill">${ROLE_LABELS[STATE.user.role]||STATE.user.role}</span></div><nav class="nav">${navItems().map(([id,label])=>`<button data-page="${id}" class="${STATE.page===id?'active':''}">${label}</button>`).join("")}<button id="logout">Sign Out</button></nav></aside><main class="main"><div class="topbar"><div><button class="mobile-menu secondary" id="menu">☰ Menu</button><h1>${navItems().find(x=>x[0]===STATE.page)?.[1]||"Dashboard"}</h1></div><span class="pill">Currency: Robux R$</span></div><div id="view"></div></main></div>`; document.querySelectorAll("[data-page]").forEach(b=>b.onclick=()=>{STATE.page=b.dataset.page;renderApp()}); $("#logout").onclick=()=>{STATE.user=null;STATE.page="dashboard";authScreen()}; $("#menu")?.addEventListener("click",()=>$("#side").classList.toggle("open")); loadPage();}
async function loadPage(){const p=STATE.page; if(p==="dashboard")return dashboard(); if(p==="myPayroll")return myPayroll(); if(p==="paystubs")return paystubs(true); if(p==="payRequests")return requestPage("payRequests"); if(p==="raiseRequests")return requestPage("raiseRequests"); if(p==="adjustments")return requestPage("adjustmentRequests"); if(p==="periods")return periods(); if(p==="profiles")return profiles(); if(p==="expenses")return logsPage("expenseLogs"); if(p==="revenue")return logsPage("revenueLogs"); if(p==="audits")return audits(); if(p==="approvals")return approvals(); if(p==="employees")return employees(); if(p==="auditLog")return auditLog();}
async function dashboard(){const [pay,reqs,raises,exps,revs]=await Promise.all([all("paystubs"),all("payRequests"),all("raiseRequests"),all("expenseLogs"),all("revenueLogs")]); const visible=can("canViewFinanceRecords")?pay:pay.filter(x=>x.employeeId===STATE.user.employeeId); const unpaid=visible.filter(x=>x.paymentStatus!=="Paid").reduce((s,x)=>s+Number(x.finalRobuxAmount||0),0); const pending=reqs.filter(x=>x.status==="Pending").length+raises.filter(x=>x.status==="Pending").length; const expenses=exps.filter(x=>x.status!=="Deleted").reduce((s,x)=>s+Number(x.amount||0),0); const revenue=revs.filter(x=>x.status!=="Deleted").reduce((s,x)=>s+Number(x.amount||0),0); $("#view").innerHTML=`<section class="section"><div class="cards"><div class="card"><small>Visible Unpaid Payroll</small><div class="stat">${money(unpaid)}</div></div><div class="card"><small>Pending Approvals</small><div class="stat">${pending}</div></div><div class="card"><small>Total Revenue Logged</small><div class="stat">${money(revenue)}</div></div><div class="card"><small>Total Expenses Logged</small><div class="stat">${money(expenses)}</div></div></div><div class="card"><h2>Portal Rules</h2><p>Staff can view their pay, paystubs, and requests. Finance Employee+ can maintain records. FC Supervisor can adjust payroll. CFO+ can lock periods. Board+ can edit/delete logs. Executives/Owner approve pay and raise requests.</p></div></section>`;}
async function myPayroll(){const stubs=(await all("paystubs")).filter(x=>x.employeeId===STATE.user.employeeId); const profile=(await getDoc(doc(db,"payrollProfiles",STATE.user.payrollId))).data()||{}; const balance=stubs.filter(x=>x.paymentStatus!=="Paid").reduce((s,x)=>s+Number(x.finalRobuxAmount||0),0); $("#view").innerHTML=`<section class="section"><div class="cards"><div class="card"><small>Payroll ID</small><div class="stat">${STATE.user.payrollId}</div></div><div class="card"><small>Pay Rate</small><div class="stat">${money(STATE.user.payRate||0)}</div><small>${STATE.user.payRateType||"Per Ticket/Quota"}</small></div><div class="card"><small>Eligible to Request</small><div class="stat">${money(balance)}</div></div><div class="card"><small>Lifetime Paid</small><div class="stat">${money(profile.lifetimePaid||0)}</div></div></div><div class="actions"><button onclick="window.CS.openPayRequest()">Request Payout</button><button class="secondary" onclick="window.CS.openRaiseRequest()">Request Raise</button><button class="secondary" onclick="window.CS.openAdjustment()">Request Adjustment</button></div></section>`;}
async function paystubs(own=false){let data=await all("paystubs"); if(own||!can("canViewFinanceRecords"))data=data.filter(x=>x.employeeId===STATE.user.employeeId); tableView("Paystubs",data,["paystubId","periodId","employeeName","payrollId","ticketsCompleted","baseEarnings","bonusPay","adjustments","deductions","finalRobuxAmount","requestStatus","paymentStatus"], can("canPreparePayroll")?`<button onclick="window.CS.openPaystub()">New Paystub</button>`:"");}
function tableView(title,data,cols,toolbar=""){ $("#view").innerHTML=`<section class="section"><div class="toolbar"><h2>${title}</h2><div class="actions">${toolbar}</div></div><div class="table-wrap"><table><thead><tr>${cols.map(c=>`<th>${c}</th>`).join("")}<th>Actions</th></tr></thead><tbody>${data.length?data.map(r=>`<tr>${cols.map(c=>`<td>${c.toLowerCase().includes("amount")||c.toLowerCase().includes("earn")||c.toLowerCase().includes("pay")||c.toLowerCase().includes("deduct")?money(r[c]):(r[c]??"")}</td>`).join("")}<td>${rowActions(title,r)}</td></tr>`).join(""):`<tr><td colspan="${cols.length+1}" class="empty">No records yet.</td></tr>`}</tbody></table></div></section>`;}
function rowActions(title,r){let a=[]; if(title.includes("Expense")||title.includes("Revenue")){ if(can("canEditAnyLog")||can("canMaintainFinanceRecords"))a.push(`<button class="secondary" onclick="window.CS.editLog('${title.includes("Expense")?'expenseLogs':'revenueLogs'}','${r.id}')">Edit</button>`); if(can("canDeleteAnyLog"))a.push(`<button class="danger" onclick="window.CS.deleteLog('${title.includes("Expense")?'expenseLogs':'revenueLogs'}','${r.id}')">Delete</button>`)} if(title==="Employees"&&can("canManageUsers")){a.push(`<button class="secondary" onclick="window.CS.resetPin('${r.employeeId}')">Reset PIN</button>`)} return a.join(" ");}
async function requestPage(col){let data=await all(col); if(!can("canViewFinanceRecords")&&!can("canApprovePayRequests"))data=data.filter(x=>x.employeeId===STATE.user.employeeId); const map={payRequests:["requestId","employeeName","payrollId","paystubId","requestedAmount","status","reason"],raiseRequests:["requestId","employeeName","payrollId","currentPayRate","requestedPayRate","status","reason"],adjustmentRequests:["requestId","employeeName","payrollId","type","status","reason"]}; const names={payRequests:"Pay Requests",raiseRequests:"Raise Requests",adjustmentRequests:"Adjustment Requests"}; const btn=col==="payRequests"?`<button onclick="window.CS.openPayRequest()">Request Payout</button>`:col==="raiseRequests"?`<button onclick="window.CS.openRaiseRequest()">Request Raise</button>`:`<button onclick="window.CS.openAdjustment()">Request Adjustment</button>`; tableView(names[col],data,map[col],btn);}
async function periods(){const data=await all("payrollPeriods"); tableView("Payroll Periods",data,["periodId","startDate","endDate","status","lockedBy","lockedAt"],`<button onclick="window.CS.openPeriod()">New Period</button>`)}
async function profiles(){const data=await all("payrollProfiles"); tableView("Payroll Profiles",data,["payrollId","employeeId","payrollStatus","currentBalance","lifetimePaid","lastPaymentDate"],"")}
async function logsPage(col){const data=(await all(col)).filter(x=>x.status!=="Deleted"||can("canDeleteAnyLog")); tableView(col==="expenseLogs"?"Expense Logs":"Revenue Logs",data,[col==="expenseLogs"?"expenseId":"revenueId","date",col==="expenseLogs"?"payee":"source","category","amount","status","description","addedBy"],`<button onclick="window.CS.openLog('${col}')">New ${col==="expenseLogs"?"Expense":"Revenue"}</button>`)}
async function audits(){let data=await all("managementAudits"); if(!can("canViewFinanceRecords"))data=data.filter(x=>x.managerEmployeeId===STATE.user.employeeId); tableView("Management Audits",data,["auditId","managerName","subjectEmployeeId","payrollId","periodId","auditType","status","recommendation"],`<button onclick="window.CS.openAudit()">New Audit</button>`)}
async function approvals(){const [p,r,a]=await Promise.all([all("payRequests"),all("raiseRequests"),all("adjustmentRequests")]); const rows=[...p.map(x=>({...x,kind:"Pay"})),...r.map(x=>({...x,kind:"Raise"})),...a.map(x=>({...x,kind:"Adjustment"}))].filter(x=>["Pending","Under Review"].includes(x.status)); $("#view").innerHTML=`<section class="section"><h2>Pending Approval Queue</h2><div class="table-wrap"><table><thead><tr><th>Kind</th><th>Request</th><th>Employee</th><th>Amount/Rate</th><th>Reason</th><th>Actions</th></tr></thead><tbody>${rows.length?rows.map(x=>`<tr><td>${x.kind}</td><td>${x.requestId}</td><td>${x.employeeName}</td><td>${money(x.requestedAmount||x.requestedPayRate||0)}</td><td>${x.reason||""}</td><td><button onclick="window.CS.decide('${x.kind}','${x.id}','Approved')">Approve</button> <button class="danger" onclick="window.CS.decide('${x.kind}','${x.id}','Denied')">Deny</button></td></tr>`).join(""):`<tr><td colspan="6" class="empty">No pending approvals.</td></tr>`}</tbody></table></div></section>`}
async function employees(){const data=await all("users"); tableView("Employees",data,["employeeName","employeeId","department","rank","payrollId","discordUsername","discordId","role","accountStatus"],`<button onclick="window.CS.openEmployee()">Add Employee</button>`)}
async function auditLog(){const data=(await all("auditLogs")).sort((a,b)=>(b.createdAtText||"").localeCompare(a.createdAtText||"")); tableView("Audit Log",data,["createdAtText","action","target","actorName","actorEmployeeId"],"")}
function modal(html){document.body.insertAdjacentHTML("beforeend",`<div class="modal-backdrop"><div class="modal">${html}</div></div>`); document.querySelector(".modal-backdrop").onclick=e=>{if(e.target.className==="modal-backdrop")e.target.remove()}}
function closeModal(){document.querySelector(".modal-backdrop")?.remove()}
window.CS={
openEmployee(){modal(`<h2>Add Staff Member</h2><form id="emp" class="grid"><div class="form-row"><label>Employee Name<input name="employeeName" required></label><label>Employee ID<input name="employeeId" required placeholder="COG-FIN-001"></label></div><div class="form-row"><label>Discord Username<input name="discordUsername" required></label><label>Discord User ID<input name="discordId" required></label></div><div class="form-row"><label>Department<input name="department" required></label><label>Rank<input name="rank" required></label></div><div class="form-row"><label>Payroll ID<input name="payrollId" required placeholder="CS-1206"></label><label>Pay Rate R$<input name="payRate" type="number" min="0" value="0"></label></div><div class="form-row"><label>Pay Rate Type<input name="payRateType" placeholder="Per Ticket"></label><label>Role<select name="role">${Object.entries(ROLE_LABELS).map(([k,v])=>`<option value="${k}">${v}</option>`).join("")}</select></label></div><button>Create Employee</button></form>`);$("#emp").onsubmit=async e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.target));const rec={...f,payRate:Number(f.payRate||0),permissions:ROLE_PERMS[f.role]||ROLE_PERMS.staff,pinHash:null,pinSalt:null,firstLoginComplete:false,accountStatus:"Pending Activation",payrollStatus:"Active",createdAt:serverTimestamp(),createdBy:STATE.user.employeeId};await setDoc(doc(db,"users",rec.employeeId),rec);await setDoc(doc(db,"payrollProfiles",rec.payrollId),{employeeId:rec.employeeId,payrollId:rec.payrollId,payrollStatus:"Active",currentBalance:0,lifetimePaid:0,createdAt:serverTimestamp()});await audit("employee_created",{employeeId:rec.employeeId,payrollId:rec.payrollId},rec.employeeId);closeModal();renderApp();}},
openPeriod(){modal(`<h2>Create Payroll Period</h2><form id="period" class="grid"><div class="form-row"><label>Period ID<input name="periodId" value="PP-${new Date().getFullYear()}-${String(Math.ceil((new Date().getMonth()*30+new Date().getDate())/14)).padStart(3,'0')}"></label><label>Status<select name="status"><option>Open</option><option>Under Review</option><option>Locked</option><option>Pay Requests Open</option><option>Paid</option><option>Archived</option></select></label></div><div class="form-row"><label>Start Date<input name="startDate" type="date" required></label><label>End Date<input name="endDate" type="date" required></label></div><button>Create Period</button></form>`);$("#period").onsubmit=async e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.target));await setDoc(doc(db,"payrollPeriods",f.periodId),{...f,createdAt:serverTimestamp(),createdBy:STATE.user.employeeId});await audit("payroll_period_created",f,f.periodId);closeModal();renderApp();}},
openPaystub(){modal(`<h2>Create Paystub</h2><form id="stub" class="grid"><div class="form-row"><label>Employee ID<input name="employeeId" required></label><label>Payroll ID<input name="payrollId" required></label></div><div class="form-row"><label>Employee Name<input name="employeeName" required></label><label>Period ID<input name="periodId" required></label></div><div class="form-row"><label>Tickets Completed<input name="ticketsCompleted" type="number" value="0"></label><label>Base Earnings R$<input name="baseEarnings" type="number" value="0"></label></div><div class="form-row"><label>Bonus R$<input name="bonusPay" type="number" value="0"></label><label>Adjustments R$<input name="adjustments" type="number" value="0"></label></div><div class="form-row"><label>Deductions/Holds R$<input name="deductions" type="number" value="0"></label><label>Status<select name="paymentStatus"><option>Eligible to Request</option><option>Held</option><option>Paid</option></select></label></div><label>Notes<textarea name="notes"></textarea></label><button>Create Paystub</button></form>`);$("#stub").onsubmit=async e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.target));const final=Number(f.baseEarnings||0)+Number(f.bonusPay||0)+Number(f.adjustments||0)-Number(f.deductions||0);const paystubId=`PS-${f.periodId.replace('PP-','')}-${f.payrollId.replace(/[^0-9]/g,'')||Date.now()}`;await setDoc(doc(db,"paystubs",paystubId),{...f,paystubId,baseEarnings:Number(f.baseEarnings||0),bonusPay:Number(f.bonusPay||0),adjustments:Number(f.adjustments||0),deductions:Number(f.deductions||0),ticketsCompleted:Number(f.ticketsCompleted||0),finalRobuxAmount:final,requestStatus:"Not Requested",preparedBy:STATE.user.employeeId,createdAt:serverTimestamp()});await audit("paystub_created",{paystubId,final},paystubId);closeModal();renderApp();}},
openPayRequest(){modal(`<h2>Request Payout</h2><form id="payreq" class="grid"><label>Paystub ID<input name="paystubId" required placeholder="Example: PS-2026-013-1205"></label><label>Requested Amount R$<input name="requestedAmount" type="number" min="1" required></label><label>Reason<textarea name="reason" placeholder="Requesting payout from this paystub."></textarea></label><button>Submit Request</button></form>`);$("#payreq").onsubmit=async e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.target));const requestId=idSeq("PR");await addDoc(collection(db,"payRequests"),{...f,requestId,requestedAmount:Number(f.requestedAmount),employeeId:STATE.user.employeeId,employeeName:STATE.user.employeeName,payrollId:STATE.user.payrollId,status:"Pending",submittedAt:serverTimestamp(),submittedAtText:now()});await audit("pay_request_submitted",{requestId},requestId);closeModal();renderApp();}},
openRaiseRequest(){modal(`<h2>Request Raise</h2><form id="raise" class="grid"><div class="form-row"><label>Current Pay Rate R$<input name="currentPayRate" type="number" value="${STATE.user.payRate||0}"></label><label>Requested Pay Rate R$<input name="requestedPayRate" type="number" required></label></div><label>Reason<textarea name="reason" required></textarea></label><button>Submit Raise Request</button></form>`);$("#raise").onsubmit=async e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.target));const requestId=idSeq("RR");await addDoc(collection(db,"raiseRequests"),{...f,requestId,currentPayRate:Number(f.currentPayRate),requestedPayRate:Number(f.requestedPayRate),employeeId:STATE.user.employeeId,employeeName:STATE.user.employeeName,payrollId:STATE.user.payrollId,status:"Pending",submittedAt:serverTimestamp(),submittedAtText:now()});await audit("raise_request_submitted",{requestId},requestId);closeModal();renderApp();}},
openAdjustment(){modal(`<h2>Request Payroll Adjustment</h2><form id="adj" class="grid"><label>Type<select name="type"><option>Missing ticket count</option><option>Incorrect quota count</option><option>Wrong pay rate</option><option>Missing bonus</option><option>Wrong deduction</option><option>Status issue</option><option>Other correction</option></select></label><label>Reason<textarea name="reason" required></textarea></label><button>Submit Adjustment</button></form>`);$("#adj").onsubmit=async e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.target));const requestId=idSeq("AR");await addDoc(collection(db,"adjustmentRequests"),{...f,requestId,employeeId:STATE.user.employeeId,employeeName:STATE.user.employeeName,payrollId:STATE.user.payrollId,status:"Pending",submittedAt:serverTimestamp(),submittedAtText:now()});await audit("adjustment_request_submitted",{requestId},requestId);closeModal();renderApp();}},
openLog(col){const isE=col==="expenseLogs";modal(`<h2>New ${isE?"Expense":"Revenue"} Log</h2><form id="log" class="grid"><div class="form-row"><label>Date<input name="date" type="date" required></label><label>Amount R$<input name="amount" type="number" min="0" required></label></div><div class="form-row"><label>${isE?"Payee":"Source"}<input name="${isE?'payee':'source'}" required></label><label>Category<input name="category" required></label></div><label>Description<textarea name="description"></textarea></label><button>Create Log</button></form>`);$("#log").onsubmit=async e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.target));const key=isE?"expenseId":"revenueId";const id=idSeq(isE?"EXP":"REV");await addDoc(collection(db,col),{...f,[key]:id,amount:Number(f.amount),status:"Active",addedBy:STATE.user.employeeName,addedById:STATE.user.employeeId,createdAt:serverTimestamp()});await audit(`${isE?'expense':'revenue'}_log_created`,{id},id);closeModal();renderApp();}},
async editLog(col,id){const ref=doc(db,col,id);const rec=(await getDoc(ref)).data();const amount=prompt("Amount R$",rec.amount); if(amount===null)return; const description=prompt("Description",rec.description||""); await updateDoc(ref,{amount:Number(amount),description,updatedBy:STATE.user.employeeId,updatedAt:serverTimestamp()}); await audit(`${col}_edited`,{id,amount},id); renderApp();},
async deleteLog(col,id){const reason=prompt("Reason for deleting/voiding this log:"); if(!reason)return; await updateDoc(doc(db,col,id),{status:"Deleted",deletedBy:STATE.user.employeeId,deletedAt:serverTimestamp(),deleteReason:reason}); await audit(`${col}_soft_deleted`,{id,reason},id); renderApp();},
openAudit(){modal(`<h2>New Management Audit</h2><form id="audit" class="grid"><div class="form-row"><label>Subject Employee ID<input name="subjectEmployeeId" required></label><label>Payroll ID<input name="payrollId"></label></div><div class="form-row"><label>Period ID<input name="periodId"></label><label>Audit Type<input name="auditType" value="Payroll/Performance Review"></label></div><label>Findings<textarea name="findings" required></textarea></label><label>Recommendation<textarea name="recommendation"></textarea></label><button>Submit Audit</button></form>`);$("#audit").onsubmit=async e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.target));const auditId=idSeq("MA");await addDoc(collection(db,"managementAudits"),{...f,auditId,managerEmployeeId:STATE.user.employeeId,managerName:STATE.user.employeeName,status:"Submitted",submittedAt:serverTimestamp()});await audit("management_audit_submitted",{auditId},auditId);closeModal();renderApp();}},
async decide(kind,id,status){let col=kind==="Pay"?"payRequests":kind==="Raise"?"raiseRequests":"adjustmentRequests"; const notes=prompt(`${status} notes:`)||""; await updateDoc(doc(db,col,id),{status,reviewedBy:STATE.user.employeeId,reviewedAt:serverTimestamp(),decisionNotes:notes}); await audit(`${kind.toLowerCase()}_request_${status.toLowerCase()}`,{id,notes},id); renderApp();},
async resetPin(employeeId){if(!confirm("Reset this employee's PIN? Their next login will require a new PIN."))return; await updateDoc(doc(db,"users",employeeId),{pinHash:null,pinSalt:null,firstLoginComplete:false,accountStatus:"Pending Activation",failedPinAttempts:0,pinLockedUntil:null}); await audit("pin_reset",{employeeId},employeeId); renderApp();}
};
init();
